object Feature {
    const val ADD_PAYMENT = ":features:add-payment"
    const val SPLASH = ":features:splash"
    const val LOGIN = ":features:login"
    const val COMPLAINT = ":features:complaint"
    const val USER_FORM = ":features:user-data"
    const val SET_PASSWORD = ":features:set-password"
    const val TICKET = ":features:ticket"
    const val SUGGESTION = ":features:suggestion"
    const val SIGN_UP = ":features:signup"
    const val RESET_PASSWORD = ":features:reset-password"
    const val PROFILE = ":features:profile"
    const val BOOKING = ":features:booking"
    const val EDIT_PROFILE = ":features:edit-profile"
    const val FORGET_PASSWORD = ":features:forget-password"
    const val ROUTE = ":features:route"
    const val LINE_MAP = ":features:line-map"
    const val HOME = ":features:home-screen"
    const val MAP = ":features:map"
    const val SCAN_QR = ":features:scan-qr"
    const val SEND_OTP = ":features:send-otp"
    const val APP_SETTINGS = ":features:app-settings"
    const val SELECT_SERVICE = ":features:select-service"
    const val SELECT_STATION = ":features:select-station"
    const val SELECT_SEAT = ":features:select-seat"
    const val SELECT_TRIP = ":features:select-trip"
}